version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "01:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: concurrently
        versions:
          - 6.0.0
          - 6.0.1
      - dependency-name: "@octokit/webhooks"
        versions:
          - 7.24.3
          - 8.12.0
          - 8.12.2
          - 8.3.0
          - 8.4.1
          - 8.5.3
          - 8.5.4
          - 8.7.0
          - 8.8.0
      - dependency-name: typescript
        versions:
          - 4.2.2
          - 4.2.3
