name: Release management

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: Thanks! Release {release_link} addresses this.
          label-template: ":dart: landed,release-{release_tag}"
          skip-label: dependencies

      - uses: apexskier/github-semver-parse@v1
        id: semver
        with:
          version: ${{ github.event.release.tag_name }}

      # These use GITHUB_TOKEN, so they won't recurse and create more releases

      - name: Tag
        if: ${{ !steps.semver.outputs.prerelease && steps.semver.outputs.version }}
        uses: richardsimko/update-tag@v1.0.4
        with:
          tag_name: ${{ format('v{0}', steps.semver.outputs.major) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag latest
        if: ${{ !steps.semver.outputs.prerelease && steps.semver.outputs.version }}
        uses: richardsimko/update-tag@v1.0.4
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
